### ISSUE TITLE
PHP error on login

### ISSUE THREAD

**Issue by theoneandonly-vector** [interference-security/empire-web#10]
http://192.168.0.12/login.php says:
Failed login attempt.

apache2-error.log:
PHP Warning: array_key_exists() expects parameter 2 to be array, null given in /var/www/html/login.php line 35, referer: http://192.168.0.12/login.php

When I try to connect to the API on this device via empire-web on a 2nd Device it works!
So the Powershell-Empire isn't the problem here.

**Comment by theoneandonly-vector** [comment]
in the terminal it shows me it as installed + activated:

root@kali:/var/www/html# php -i | grep -i curl
/etc/php5/cli/conf.d/20-curl.ini,
curl
cURL support => enabled
cURL Information => 7.52.1
root@kali:/var/www/html# php -v
PHP 5.6.7-1 (cli) (built: Mar 24 2015 13:43:55)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2015, by Zend Technologies

**Comment by theoneandonly-vector** [comment]
update:
forgot to set the permissions on the two test.php's

now you test.php gives me:
Curl found

**Comment by theoneandonly-vector** [comment]
apache2 error-log:
NU nano 2.7.4                        File: /var/log/apache2/error.log                                  [Wed Feb 08 10:57:22.791666 2017] [:error] [pid 2977] [client 127.0.0.1:38603] PHP Warning:  array_key_ex$

**Comment by theoneandonly-vector** [comment]
Error:
[Wed Feb 08 13:52:28.150471 2017] [core:notice] [pid 15495] AH00094: Command line: '/usr/sbin/apache2'
[Wed Feb 08 13:53:32.831181 2017] [:error] [pid 15503] [client 127.0.0.1:39042] PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /var/www/html/login.php on line 35, referer: http://127.0.0.1/login.php

**Comment by interference-security** [comment]
Thank you for raising this issue and sharing all the details you could. I will look into and get back to you soon.

**Comment by theoneandonly-vector** [comment]
any update?

**Comment by interference-security** [comment]
I tested using Empire version 1.6.0 and 2.0_beta but could not reproduce the issue you have reported. I request you to ensure that your configuration and setup is correct then try again. Feel free to update this thread or close it if solved.

**Comment by theoneandonly-vector** [comment]
I use 1.6.0 
everything in empire works. As I already wrote. I can connect to the Empire-API (on this machine) using empire-web hosted on a different machine.

just as an addition.
The machine, which isn't working runs Kali using Nethunter.

**Comment by interference-security** [comment]
I am not sure what is wrong with your setup. After analyzing Empire Web and Empire projects, it does not seem to be an issue with these projects.

**Comment by le4f** [comment]
I have also encountered this error.

environment: docker pull eboraas/apache-php
error: PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /var/www/html/test/login.php on line 35

php -i | grep -i curl
```
/etc/php5/cli/conf.d/20-curl.ini,
curl
cURL support => enabled
cURL Information => 7.38.0
```

thx

**Comment by interference-security** [comment]
Try running the following command and check if it returns a token:
`curl -i -k -H "Content-Type: application/json" https://EMPIRE_SERVER:EMPIRE_REST_PORT/api/admin/login -X POST -d '{"username":"EMPIRE_USERNAME", "password":"EMPIRE_PASSWORD"}`

Replace the values of EMPIRE_SERVER, EMPIRE_REST_PORT, EMPIRE_USERNAME and EMPIRE_PASSWORD.

Reference: https://github.com/EmpireProject/Empire/wiki/RESTful-API#api-authentication

**Comment by le4f** [comment]
this fix 
[https://github.com/EmpireProject/Empire/pull/329/files/9bbcb0d7ce11adfad7ae500d63e91b9950d74150](https://github.com/EmpireProject/Empire/pull/329/files/9bbcb0d7ce11adfad7ae500d63e91b9950d74150)
thx again

**Comment by theoneandonly-vector** [comment]
doesn't fix it for me (already applied) even copied the files (both empire
and empire-web) from a working machine.

Am 22.02.2017 3:41 vorm. schrieb "Le4F" <notifications@github.com>:
