### ISSUE TITLE
php 7 Internat Server Error (500)

### ISSUE THREAD

**Issue by CorpOfHack** [interference-security/empire-web#12]
Hello,please tell is it working on php7 or not??
If working on php7 , how I can solve this problem?

**php -i | grep -i curl** >>>
/etc/php/7.0/cli/conf.d/20-curl.ini,
curl
cURL support => enabled
cURL Information => 7.52.

Here is screenshots:

http://i.piccy.info/i9/1e507c7d160f3977670d25413e407a0e/1491760123/73402/1136357/2017_04_09_204332_875x517_scrot.png

http://i.piccy.info/i9/c57d06c65c33481a80c2910ec7d427ae/1491760177/118153/1136357/2017_04_09_204802_1023x211_scrot.png

**Comment by mdfkbtc** [comment]
corpOFhack try this >  sudo apt-get install php-curl
                                    sudo service apache2 restart 
it should work ford u
