### ISSUE TITLE
'Create a new listener', Error "Unexpected response".

### ISSUE THREAD

**Issue by ralpy** [interference-security/empire-web#14]
I need a help. Please. What's wrong?

**Comment by necony286** [comment]
the empire syntax has been changed  for creating listener.

**Comment by interference-security** [comment]
We are working on releasing a new version of Empire Web which will support Empire 2.0. Due to the changes in REST API introduced in Empire 2.0 you are seeing the "Unexpected Response" error message.

**Comment by tehseensagar** [comment]
I'm having the same issue , how long does it take to release 2.0 version of web.

Regards

**Comment by interference-security** [comment]
Dev branch for Empire Web 2.0 has been created: https://github.com/interference-security/empire-web/tree/dev

Please note that everything is not working. Happy to answer your questions and fix bugs.

**Comment by berm0427** [comment]
but, still cause error

**Comment by interference-security** [comment]
Empire Web is going under a complete redesign. All the reported bugs are duly noted and best efforts will be made to resolve them in the upcoming release. The new code will be made available in dev branch in coming weeks.

**Comment by killercoderz4** [comment]
is empire web stil an ongoing project. development seems to have stalled

**Comment by interference-security** [comment]
I have not been able to give enough time to this project due to which progress in development is not very good. However, we have seen contribution from users like grimreap124. Every contribution counts and that's how we can see bug fixes and new features. I will try to give some time to this.

**Comment by interference-security** [comment]
It has been fixed in Empire Web v2.0 release. Please feel free to reopen this issue if it is still not fixed.
