### ISSUE TITLE
empire-dev & empire-web dev ver setting...

### ISSUE THREAD

**Issue by ayanamirins** [interference-security/empire-web#16]
I'm testing empier-empier-web with all the dev versions, but when I run the 'launcher_bat' on the victim's computer, the agent will not connect at all.
What is the problem? The listener type is set to http_foreign. Is there a need to change the listener settings?

**Comment by interference-security** [comment]
Agents are not working when listener type is "http_foreign". It is working when listener type is "http". Since this is a development version of empire-web, all these issues will be issued as the development progresses. As of now, I am not sure if it is an issue with Empire or Empire-Web.

**Comment by interference-security** [comment]
It has been fixed in Empire Web v2.0 release. Please feel free to reopen this issue if it is still not fixed.
