### ISSUE TITLE
Empire Web cannot login

### ISSUE THREAD

**Issue by zondaime13** [interference-security/empire-web#19]
![screenshot](https://user-images.githubusercontent.com/26117234/32985005-0f9002ba-cce3-11e7-82ba-39b6c35084d1.png)
Hello everyone. Today I tried to install empire-web on my computer and I got this error. I tried many ways like chmod 777 empire's folder, apt-get update and upgrade, apache2 restart but it's still not working. So, I will be so glad if anyone can help me to solve that. Thank you! 
PS: The default login of Empire still work, but it is empty/blank when I clicking to "Login" :( :( :(

**Comment by interference-security** [comment]
What is the error message? Cannot see it in your posted issue.
