### ISSUE TITLE
heroku instance login issue

### ISSUE THREAD

**Issue by killercoderz4** [interference-security/empire-web#25]
good day.  chose your heroku deploy option and everything deployed smoothly in a minute. now being that it was automated deployment , i dont know the ip and port or username and password for empire login. how can i get it. since heroku did all the manual work and auto deployed the app

**Comment by interference-security** [comment]
Login IP address, port, username and password are of your Empire REST API server running on a public server that you might have. Heroku will only give you a web interface to interact with Empire which it should be able to reach.
