### ISSUE TITLE
not login

### ISSUE THREAD

**Issue by tennc** [interference-security/empire-web#3]
when i write host  ip  name password  ,  login ，then HTTP ERROR 500

![gif](https://cloud.githubusercontent.com/assets/670357/15004520/a8adae6c-11ea-11e6-9d22-94801c634878.gif)

![12](https://cloud.githubusercontent.com/assets/670357/15004565/1d4c5a0c-11eb-11e6-884e-ba8613022530.jpg)

**Comment by interference-security** [comment]
It seems you do not have PHP Curl installed or enabled. I have updated the [README.md](https://github.com/interference-security/empire-web/blob/master/README.md) file to help anyone who is setting up Empire Web.
Please refer the update README.md file section "[Requirements](https://github.com/interference-security/empire-web/blob/master/README.md#requirements)".

Let me know if you need further help.

If the issue gets resolved, please feel free to close the issue.

**Comment by tennc** [comment]
now can login  but have other bug,
can't Generate Stager

![1](https://cloud.githubusercontent.com/assets/670357/15008946/3425f8a2-1216-11e6-8333-bbfe7b8b31fb.jpg)

![2](https://cloud.githubusercontent.com/assets/670357/15008952/3f68ba60-1216-11e6-851c-a254b98a6518.jpg)

**Comment by interference-security** [comment]
Glad to know your login issue has been resolved.

The issue you have mentioned now is in PowerShell Empire. I have filed a [pull request](https://github.com/PowerShellEmpire/Empire/pull/205/commits/c82682262f93621227b35086406c3faab4103bd0) to get it fixed.
If you want a fixed version please refer to my fork here: https://github.com/interference-security/Empire/

What has changed:
Added following two lines in "empire" file after line 323:
```
f = open(stagerOut['OutFile']['Value'],"w")
f.write(stager.generate())
```

**Comment by tennc** [comment]
yes  it runing ok~~
