### ISSUE TITLE
GUI issue

### ISSUE THREAD

**Issue by duckthomas** [interference-security/empire-web#4]
Every connection attempt I make results in a 403, and I have no idea how to resolve it. I presume based on the 403 that it's looking for the files related to the GUI, I don't know where those go. I've tried placing them in /var/www, /var/www/html, inside Empire, and left alone in the clone location. 

Freshly updated Kali 64-bit through apt-get update && apt-get upgrade
Freshly cloned Empire and empire-web
Successfully installed and tested Empire and php5-curl

Empire Web launched in this manner: root@kali:~/Empire# ./empire --headless  --restport 443 --rest --username root --password toor

Results in:
[*] Loading modules from: /root/Empire/lib/modules/
 * Starting Empire RESTful API on port: 443
 * RESTful API token: xj3jhhapa28c3u4kot0ljqdyjtwf7foc38cd9o3a
 * Running on https://0.0.0.0:443/ (Press CTRL+C to quit)
172.16.38.141 - - [12/May/2016 10:36:01] "GET / HTTP/1.1" 403 -
127.0.0.1 - - [12/May/2016 10:46:57] "GET / HTTP/1.1" 403 -

**Comment by interference-security** [comment]
Create a file info.php in your document root direcoty (Kali Linux: /var/www/html/) with the following contents and try accessing it:
```
<?php phpinfo(); ?>
```
See if you are able to access the file in a web browser or it shows 403.

Make sure your user is allowed to access files in web server document root and permissions are properly set.

**Comment by duckthomas** [comment]
It asks me to open it with gedit. Same behavior in Ubuntu. 
I assume it's not the project, but my own shortcomings.

**Comment by interference-security** [comment]
If the info.php test failed then it is some issue with your setup. Please close the issue if you agree.

**Comment by duckthomas** [comment]
I think it might be, but is there any specific place I need to put the files? Outside of the install instructions, I have no idea what I'm missing after following the directions for both Empire and empire-web.

**Comment by interference-security** [comment]
Try booting into a Kali Linux Live Mode and then setup Empire and Empire Web then see if it works.

You can also remove PHP along with the configuration files and then re-install it with proper configuration.
