### ISSUE TITLE
Authentication Failed

### ISSUE THREAD

**Issue by michaelkhana** [interference-security/empire-web#8]
I've successfully installed the empire-powershell its running fine. But web interface its not getting me logged in.

Step1: I set password during installation process and user name already defined in db file in setup folder.

Step2:  ./empire --headless --restport 1022 --username empireadmin --password xxxx

Step3: opening web browser and filling IP , Port , Username , Password and it failed .

Can you please fix this issue.

**Comment by interference-security** [comment]
It is a bug in Empire. Please refer this: https://github.com/interference-security/empire-web/blob/master/README.md#authentication-failed-bug
