### ISSUE TITLE
issues starting with --port --username  --password

### ISSUE THREAD

**Issue by tehseensagar** [interference-security/empire-web#9]
I've applyed the fix as I ran just ./empire it works like a charm but when I supply the user/pass/port parameters I got bunch of errors.

`./empire --headless --restport 1337 --username admin --password temp1234

 * Starting a full Empire instance
[*] Loading modules from: /opt/Empire-master/lib/modules/
 * Starting Empire RESTful API on port: 1337
 * RESTful API token: gjibeplwpkwkl4auzcj5452kk6vibj0rpkctrm3i
Traceback (most recent call last):
  File "./empire", line 1234, in <module>
    start_restful_api(startEmpire=True, suppress=True, username=args.username, password=args.password, port=args.restport)
  File "./empire", line 1081, in start_restful_api
    if not request.json or not 'username' in request.json or not 'password' in request.json:
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 343, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 302, in _get_current_object
    return self.__local()
  File "/usr/local/lib/python2.7/dist-packages/flask/globals.py", line 37, in _lookup_req_object
    raise RuntimeError(_request_ctx_err_msg)
RuntimeError: Working outside of request context.

This typically means that you attempted to use functionality that needed
an active HTTP request.  Consult the documentation on testing for
information about how to avoid this problem.`

**Comment by interference-security** [comment]
This is an issue in Empire (https://github.com/adaptivethreat/empire) and not Empire Web. Empire Web is a web interfaced which uses the REST API implemented by Empire. If there is a bug or issue in Empire, it needs to be filed here: https://github.com/adaptivethreat/empire
